# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edcfd3169cc592428763fba92dae2cc1e5505c8c3b7e9657477a1688379db168bb36351622a9197d149d1055ddeaf9383acea8bdb1e7628a50663260f9c1e725

test:
  secret_key_base: ed3d2e8e880e6aa047b35ee30839e7951e7a3d5b67bc54bf28248083dfa543c5764544cb93fe8709f352a1b36c038d364fba593894b8dd3b940a1c264b3f3ad3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
